name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Create .env file
      run: |
        echo "MONGO_SRV=${{ secrets.MONGO_SRV }}" >> .env
        echo "PORT=${{ secrets.PORT }}" >> .env
    - run: npm ci
    - run: pm2 restart src/app.js
